### ISSUE TITLE
Null?

### ISSUE THREAD

**Issue by r4sas** [xcps/gostexplr#5]
<details>
  <summary>Error</summary>

```
syncedHeight is 397534
currentHeight is 399996
{ SequelizeDatabaseError: Column 'VoutId' cannot be null
    at Query.formatError (/home/gst/gostexplr/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.handler [as onResult] (/home/gst/gostexplr/node_modules/sequelize/lib/dialects/mysql/query.js:46:23)
    at Query.execute (/home/gst/gostexplr/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/home/gst/gostexplr/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/home/gst/gostexplr/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/home/gst/gostexplr/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/home/gst/gostexplr/node_modules/mysql2/lib/connection.js:79:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'SequelizeDatabaseError',
  parent:
   { Error: Column 'VoutId' cannot be null
    at Packet.asError (/home/gst/gostexplr/node_modules/mysql2/lib/packets/packet.js:684:17)
    at Query.execute (/home/gst/gostexplr/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/home/gst/gostexplr/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/home/gst/gostexplr/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/home/gst/gostexplr/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/home/gst/gostexplr/node_modules/mysql2/lib/connection.js:79:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
     code: 'ER_BAD_NULL_ERROR',
     errno: 1048,
     sqlState: '23000',
     sqlMessage: 'Column \'VoutId\' cannot be null',
     sql: '...' },
  sql: '...' }
```
</details>

<details>
  <summary>SQL</summary>

```sql
SET autocommit = 0;
START TRANSACTION;
INSERT INTO Block (
  hash,
  height,
  size,
  version,
  merkleroot,
  time,
  nonce,
  bits,
  difficulty,
  hashrate,
  previousblockhash
)
VALUES (
  "000000000003449b3d6b192f1fd23cd6ceeb597d74f4fdcbb641f937dc9f0356",
  "397535",
  "4907",
  "2",
  "18657b68d85b8a1dcb0bfc2e275f90c3930746ccc36c8c385a29c8519bb75956",
  "2019-07-01 18:25:34",
  "36127207",
  "1c00ff6b",
  "256.5794424",
  "5072821937",
  "00000000004570e98f6efa068db0a6687ecdc7f6f4d77efb915fd965c339f116"
);

INSERT INTO Transactions (
  txid,
  BlockHeight
)
VALUES (
  "70b0f2209e151e32ea37a4ff643c952be2e61dffc2ff61c023e5d9df8213826c",
  397535
);
SET @txid = LAST_INSERT_ID();

INSERT INTO Vouts (n, value)
VALUES ("0", "2.45");
SET @voutid= LAST_INSERT_ID();

INSERT IGNORE INTO Addresses (address) VALUES ("GNEDYzvY1nTU36sPQN92e9tfKtUHAUvL1g");
SET @addrid = (
  SELECT IF(
    ROW_COUNT() > 0,
    LAST_INSERT_ID(),
    (
      SELECT id
      FROM Addresses
      WHERE address='GNEDYzvY1nTU36sPQN92e9tfKtUHAUvL1g'
    )
  )
);

INSERT INTO AddressVouts (AddressId, VoutId)
VALUES (@addrid, @voutid);

INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @voutid, 1);

INSERT INTO Vouts (n, value)
VALUES ("1", "0.05");
SET @voutid= LAST_INSERT_ID();

INSERT IGNORE INTO Addresses (address) VALUES ("GJTPVtheb3QpAAdFo9BEdjrW7M8PSZw5BN");
SET @addrid = (
  SELECT IF(
    ROW_COUNT() > 0,
    LAST_INSERT_ID(),
    (
      SELECT id
      FROM Addresses
      WHERE address='GJTPVtheb3QpAAdFo9BEdjrW7M8PSZw5BN'
    )
  )
);

INSERT INTO AddressVouts (AddressId, VoutId)
VALUES (@addrid, @voutid);

INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @voutid, 1);

INSERT INTO Transactions (
  txid,
  BlockHeight
)
VALUES (
  "7e3449bbf13afe6db0fa2b916034e093e51fcf59833417ae26ed35c0b0ce5aa5",
  397535
);
SET @txid = LAST_INSERT_ID();

INSERT INTO Vouts (n, value)
VALUES ("0", "75.8323097");
SET @voutid= LAST_INSERT_ID();

INSERT IGNORE INTO Addresses (address) VALUES ("GXRXidc26PJDeG2r1grVNdZ32QfbvJGixS");
SET @addrid = (
  SELECT IF(
    ROW_COUNT() > 0,
    LAST_INSERT_ID(),
    (
      SELECT id
      FROM Addresses
      WHERE address='GXRXidc26PJDeG2r1grVNdZ32QfbvJGixS'
    )
  )
);

INSERT INTO AddressVouts (AddressId, VoutId)
VALUES (@addrid, @voutid);

INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @voutid, 1);

INSERT INTO Vouts (n, value)
VALUES ("1", "0.1176903");
SET @voutid= LAST_INSERT_ID();

INSERT IGNORE INTO Addresses (address) VALUES ("GHx12Qs8eD6SsoikV6whTpTGUGGgPPhfz3");
SET @addrid = (
  SELECT IF(
    ROW_COUNT() > 0,
    LAST_INSERT_ID(),
    (
      SELECT id
      FROM Addresses
      WHERE address='GHx12Qs8eD6SsoikV6whTpTGUGGgPPhfz3'
    )
  )
);

INSERT INTO AddressVouts (AddressId, VoutId)
VALUES (@addrid, @voutid);

INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @voutid, 1);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="ac12e0c8f7e28ebe124471a5414485e4f5605bf4c174e5c8a0459b4f88109927" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="394d29d4544600633b4beeda234982d65f1a64c087e6d38177679aeae5c8b1ff" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="52836d77dc5ba878d74f8c4033c68380403a968582d52703af567fc75e053540" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="9b66a2129c47d9db91f0ca05fa40f5ee03380119921f499967bd5eb14e943eb2" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="538460c88aeb92cb3649d6427e28dd728e0aa8f80fd41129458ac3d26dddf5e4" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="470952816e67047424d11ec3f6e432cf9d6187e57cc0cf4e6c358d2cf35303cd" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="9729d71eed3cea6d8c9a18df40b77ebeeeb2ce8370250098aeb539e67d948840" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="fa0a5d103dfec5323aa0840f5d0d131a9f5270c1c0d6f1e96dbac18b4aece614" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="271687c502ac61db6b9f55c017b1698ae8ba32774ee670c5687d2ae5802d59ab" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="dcea539dce9a730d9d0ea6f129e975bc42061bb6dff2913ca7de63565f717282" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="11d896d0af256eb512db0106a9588d265534b0a2e9c84a96cbf7054445f411fc" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="9f9c8599c701a9d4f0e01b7eedf0855a5a77e3d7a90a193b71be229bb7bd111e" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="686277dc332f0932df9a09d69fa070992cdee6252f08d2f086be5ff9c723910e" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="74c10b38ca4f370d325cc8770131b9320cbe57cb7e9f4adf0ae1e6dda84986d6" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="3e9cbcee51fa8c33933a3fcf9f0a2c67d2db4018217390139b0ed69c0b077c8b" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="ee57ac892c564c054b06ff7d679228eff04b77a8785ba7929ae4f36796ffce4c" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="148260151933683183df9db3d0d75feba5522bd10f61222804c6a637e5fe7ec8" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="b8ad4ea8cef70ae092a4212ec928e0d41a292c0a4343975ac536506050234d99" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="f415fdc78cd506db0481ab710d351c6b8d7a219fdf47e5c646e9f05c8f860e1f" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="a4030f7b9a48ca1415dacc0d33e96d755a02fe93c6624dab96b11ec015fcc76a" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="276b7476ecb66c14930ba6d25a1365258eafcbbc768770038127817ee24f8174" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="f1375ece4242eae3b274fa488d5a1b5d647f697cfc5ceeae527021bebf6d776e" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="4bd05b8541b85495cd6b2e153ff8a1adec3f2603a0e7ef7a9f65e781c0acbf8b" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="7e9f5553664141589f2216ea77602948a9aa727d6232521f419db19e32ec4148" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="9d2e0dea1d8614b161f4aa97b89a3b4a01c2a1ca6f087e8ebaf5ceb8e09b48fe" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="74a56d681824e1e550f26f6af85c45b955da9e7bbe68ee942c3e53d81c85755b" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="dc6b1a1cfcd34ba3f1fa3242ec3aaf13fa0395c9bfac42291f0407f86aab36e2" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="f7e812806367d626601ec68f2d4224cd2ddc650a44693a7db105161a9d4f20ec" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="26dcb72361bdfe5621292f6a7ac9b98eade83f054b9c637e60e97e881eb7c1f4" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="10e1e537c0065c9a134bf9916e4f72410a4cc50214fd5b9f5a51f640291cdf0d" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

SET @vin = (
  SELECT Vouts.id
  FROM Vouts
  INNER JOIN TransactionVouts
  ON Vouts.id=TransactionVouts.VoutId
  INNER JOIN Transactions
  ON Transactions.id=TransactionVouts.TransactionId
  WHERE
    TransactionVouts.direction=1 AND
    Transactions.txid="9de778edce8bbef58a46c9e753ff590298248667cc664b107a60ca2cba76d7ff" AND
    Vouts.n=0
);
INSERT INTO TransactionVouts (TransactionId, VoutId, direction)
VALUES (@txid, @vin, 0);

UPDATE Block
SET nextblockhash="000000000003449b3d6b192f1fd23cd6ceeb597d74f4fdcbb641f937dc9f0356"
WHERE hash="00000000004570e98f6efa068db0a6687ecdc7f6f4d77efb915fd965c339f116";
COMMIT;
```

</details>

**Comment by r4sas** [comment]
Хз че произошло, но получилось так, что в бд был записан отклоненный блок, и транзации `74a56d681824e1e550f26f6af85c45b955da9e7bbe68ee942c3e53d81c85755b` просто не было в бд.
Т.е. hash, merkleroot были от отклоненного блока.
Надо как то реализовать дополнительную проверку, ибо смахивает на то что оба блока почти одновременно пришли рассылкой на ноду кошеля.
Но вот отклоненный был первее, вызвалась нотификация, а потом данные в процессе обработки были изменены на уровне чейна на позже пришедший валидный блок.

**Comment by r4sas** [comment]
Добавлен оффсет импорта блоков в БД - https://github.com/xcps/gostexplr/commit/12b6a3c91eb2f05889d95986cb5912687a84a71d.
